### ISSUE TITLE
Description for each version?

### ISSUE THREAD

**Issue by aaronbell** [coz-m/MPLUS_FONTS#10]
Can you provide a basic description for each of the four font families that we can include on the Google Fonts page? 

Mplus 1
Mplus 2
Mplus 1 Code
Mplus Code Latin

Thank you!

**Comment by aaronbell** [comment]
Yes. Alternatively, you can write in Japanese and we can ask @mintoming to translate :)

**Comment by mintoming** [comment]
Yes! I can help with the translation :)
@coz-m 日本語でいただければわたくしのほうで英語化いたします（＾＾）
4-5行以内を理想としておりますので、ご参考までによろしくお願いいたします！

**Comment by coz-m** [comment]
@mintoming ありがとうございます！

**Comment by coz-m** [comment]
@mintoming 
お待たせいたしました、いかがでしょうか。


- Mplus 1
M+ FONTS は普段使い用の、ちょっと気のきいたフォントファミリーです。
Mplus 1 は Thin から Black までの 7 つのウェイトを持ち、5,700 字以上の漢字を含む日本語と GF Latin Plus に対応したサンセリフ書体です。ゆったりとした曲線と直線を組み合わせた特徴的なデザインは、小さな本文表示から大きな見出し表示まで読みやすく、文章を明るくモダンでやさしい印象にします。

- Mplus 2
M+ FONTS は普段使い用の、ちょっと気のきいたフォントファミリーです。
Mplus 2 は Thin から Black までの 7 つのウェイトを持ち、5,700 字以上の漢字を含む日本語と GF Latin Plus に対応したサンセリフ書体です。ちょっとだけクラシックな字形を残したデザインは、モダンになりすぎず、かといって従来的なデザインとも異なる、新たなスタンダード書体を目標として制作しました。

- Mplus 1 Code
M+ FONTS は普段使い用の、ちょっと気のきいたフォントファミリーです。
Mplus 1 Code は Thin から Bold までの 5 つのウェイトを持ち、5,700 字以上の漢字を含む日本語と GF Latin Plus に対応したサンセリフ書体です。プログラミング用のフォントとして小さな表示でも読みやすく、読み間違いのない字形を意識してデザインしました。Mplus 1 の全角幅日本語グリフと新設計の半角幅英数字を組み合わせた等幅フォントになっています。

- Mplus Code Latin
M+ FONTS は普段使い用の、ちょっと気のきいたフォントファミリーです。
Mplus Code Latin は Thin から Bold までの 5 つのウェイトを持ち、GF Latin Plus に対応したサンセリフ書体です。プログラミング用の等幅フォントとして小さな表示でも読みやすく、読み間違いのない字形を意識してデザインしました。文字幅 50% の Mplus Code Latin 50 と、もう少しゆったりとした文字幅 60% の Mplus Code Latin 60 の 2 種類があります。

**Comment by mintoming** [comment]
English translation:

- Mplus 1
M+ FONTS is a font family for everyday usage.
Mplus 1 is a Sans Serif font with seven weights from Thin to Black, supporting 5,700 Kanjis for Japanese with GF Latin Plus.
With the harmony of comfortable curves and straight lines, this font gives modern and generous impression, suiting for any occasions including small texts to big titles.

- Mplus 2
M+ FONTS is a font family for everyday usage.
Mplus 2 is a Sans Serif font with seven weights from Thin to Black, supporting 5,700 Kanjis for Japanese with GF Latin Plus.
With the classic letterforms, this font pursues new standard of classic modern. 

- Mplus 1 Code
M+ FONTS is a font family for everyday usage.
Mplus 1 Code is a Sans Serif font with five weights from Thin to Bold, supporting 5,700 Kanjis for Japanese with GF Latin Plus.
Because this font is for programming usage, it has high readability even in small sizes, and letterforms are designed to avoid misreadings as much as possible. This font is a combination of Mplus 1 full-width Japanese with new monospaced Latin alphabet and figures.

- Mplus Code Latin
M+ FONTS is a font family for everyday usage.
Mplus 1 Code is a Sans Serif font with five weights from Thin to Bold, supporting Japanese with GF Latin Plus.
Because this font is for programming usage, it has high readability even in small sizes, and letterforms are designed to avoid misreadings as much as possible.
There are two styles—Mplus Code Latin 50 and Mplus Code Latin 60, each having 50% and 60% character width.

**Comment by coz-m** [comment]
翻訳ありがとうございました。少しだけ気がついたのですが、

- M+ FONTS の説明の「ちょっと気のきいた」の部分を、「a little nifty」とか「a little unique」などで織り込むことはいかがでしょうか。英語圏の人がどのようなニュアンスで受け取るのか自分には分からないので判断しづらいのですが…。
- 対応漢字数の部分、5,700 字以上と表現したいので「5,700+」とか「over 5,700」にするのはいかがでしょうか。
- Mplus Code Latin の説明文。文頭が「Mplus 1 Code」になっていることと、このフォントが日本語対応しているという記述が異なっています。

以上、よろしくお願いいたします。

**Comment by coz-m** [comment]
すみません、あと一点。

- Mplus 1 Code の説明文。和文の「full-width」に対応させて、Latin を「half-width monospaced」とするのはいかがでしょうか。

**Comment by mintoming** [comment]
ご自由に変更くださって大丈夫です :)

**Comment by coz-m** [comment]
ありがとうございます。以下のようにしてみました。

- Mplus 1
M+ FONTS is a little nifty font family for everyday usage.
Mplus 1 is a Sans Serif font with seven weights from Thin to Black, supporting 5,700+ Kanjis for Japanese with GF Latin Plus.
With the harmony of comfortable curves and straight lines, this font gives modern and generous impression, suiting for any occasions including small texts to big titles.

- Mplus 2
M+ FONTS is a little nifty font family for everyday usage.
Mplus 2 is a Sans Serif font with seven weights from Thin to Black, supporting 5,700+ Kanjis for Japanese with GF Latin Plus.
With the somewhat classic letterforms, this font pursues new standard of classic modern.

- Mplus 1 Code
M+ FONTS is a little nifty font family for everyday usage.
Mplus 1 Code is a Sans Serif font with five weights from Thin to Bold, supporting 5,700+ Kanjis for Japanese with GF Latin Plus.
Because this font is for programming usage, it has high readability even in small sizes, and letterforms are designed to avoid misreadings as much as possible. This font is a combination of Mplus 1 full-width Japanese with new half-width monospaced Latin alphabet and figures.

- Mplus Code Latin
M+ FONTS is a little nifty font family for everyday usage.
Mplus Code Latin is a Sans Serif font with five weights from Thin to Bold, supporting GF Latin Plus.
Because this font is for programming usage, it has high readability even in small sizes, and letterforms are designed to avoid misreadings as much as possible.
There are two styles—Mplus Code Latin 50 and Mplus Code Latin 60, each having 50% and 60% character width.
